package com.organicmoto.maps.region

import android.content.Context
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import com.graphhopper.util.shapes.GHPoint
import com.organicmoto.maps.geocoding.GeocoderIndex
import com.organicmoto.maps.geocoding.SearchEngine
import com.organicmoto.maps.routing.GraphHopperRouter
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/**
 * On-device proof that a complete regional package really works: install the
 * committed Monaco package (generated by map-server from a real OSM extract),
 * activate it, then route and search using only its graph, geocoder, and
 * basemap — and prove that the bundled fallback comes back cleanly.
 */
@RunWith(AndroidJUnit4::class)
class RegionSwitchOnDeviceTest {

    private val context: Context
        get() = InstrumentationRegistry.getInstrumentation().targetContext

    private val registry: RegionRegistry
        get() = RegionRegistry(File(context.filesDir, "regions"))

    @Before
    fun clean() {
        File(context.filesDir, "regions").deleteRecursively()
    }

    @After
    fun restore() {
        File(context.filesDir, "regions").deleteRecursively()
    }

    private fun copyMonacoPackage(): File {
        val instrumentation = InstrumentationRegistry.getInstrumentation()
        val target = File(context.cacheDir, "monaco-test.motomap")
        instrumentation.context.assets.open("regions/monaco.motomap").use { input ->
            target.outputStream().use { output -> input.copyTo(output) }
        }
        return target
    }

    @Test
    fun installsActivatesRoutesAndSearchesInTheImportedRegion() {
        val archive = copyMonacoPackage()
        val install = registry.install(archive)
        assertEquals("monaco", install.regionId)
        assertEquals("Monaco", install.regionName)
        assertTrue(install.pipelineFingerprint.length == 64)

        val generation = registry.activate(install.installId)
        val dataset = registry.activeDataset(context)
        assertEquals(RegionKind.INSTALLED, dataset.kind)
        assertEquals("monaco", dataset.regionId)
        assertEquals(generation, dataset.generation)
        assertTrue(dataset.tilesUrl!!.startsWith("pmtiles://file://"))
        assertTrue(dataset.geocoderFile!!.isFile)

        // The package's own routing graph serves a real route.
        val router = GraphHopperRouter(context, dataset.graphDir, copyGraphFromAssets = false)
        try {
            val result = router.route(GHPoint(43.7325, 7.4189), GHPoint(43.7389, 7.4270))
            val primary = result.routes.first()
            assertTrue("expected a real distance, got ${primary.distance}", primary.distance > 0)
            assertTrue(primary.points.size() > 1)
        } finally {
            router.close()
        }

        // The package's own place-search index answers queries.
        val index = GeocoderIndex.loadFile(dataset.geocoderFile!!)
        assertTrue(index.docCount > 0)
        assertTrue(index.termCount > 0)
        val results = kotlinx.coroutines.runBlocking { SearchEngine(index).search("monaco", limit = 5) }
        assertFalse("Monaco's index should find Monaco", results.isEmpty())

        archive.delete()
    }

    @Test
    fun activationIsTransactionalAndRemovalKeepsTheActiveRegion() {
        val archive = copyMonacoPackage()
        val install = registry.install(archive)
        registry.activate(install.installId)

        // Removing the active install is refused; the data stays usable.
        try {
            registry.remove(install.installId)
            throw AssertionError("active region was removable")
        } catch (expected: RegionPackageException) {
        }
        assertEquals(install.installId, registry.activeDataset(context).installId)

        // Switching back to the bundled dataset and removing is allowed.
        val bundledGeneration = registry.activateBundled()
        val bundled = registry.activeDataset(context)
        assertEquals(RegionKind.BUNDLED, bundled.kind)
        assertEquals(bundledGeneration, bundled.generation)
        assertTrue(bundled.copyGraphFromAssets)
        registry.remove(install.installId)
        assertTrue(registry.list().isEmpty())
        archive.delete()
    }

    @Test
    fun aCorruptedActiveInstallFallsBackToBundledInsteadOfFailing() {
        val archive = copyMonacoPackage()
        val install = registry.install(archive)
        registry.activate(install.installId)

        // Corrupt the installed tiles so the active dataset cannot be trusted.
        File(File(registry.installsDir, install.dirName), RegionPackageContract.TILES_PATH)
            .writeText("corrupted")
        val dataset = registry.activeDataset(context)
        assertEquals(RegionKind.BUNDLED, dataset.kind)
        archive.delete()
    }
}
